123TribeFrameworker/Controllers/MaterialInfoController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using _123TribeFrameworker.Entity;
using _123TribeFrameworker.Models.QueryModel;
using _123TribeFrameworker.Services;
using Unity.Attributes;

namespace _123TribeFrameworker.Controllers
{
    public class MaterialInfoController : Controller
    {
        [Dependency]
        public IMaterialInfoService service { get; set; }
        // GET: MaterialInfo
        public ActionResult Index(Pager<List<MaterialInfo>> pager, MaterialInfoQuery condition)
        {
            ViewBag.condition = condition;
            pager = service.searchByCondition(pager, condition);
            return View(pager);
        }
        public ActionResult add()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> add(MaterialInfo model)
        {
            if (ModelState.IsValid)
            {
                var result = await service.addAsync(model);
                if (!result.success)
                {
                    ModelState.AddModelError("", result.message);
                }
                else
                {
                    ModelState.AddModelError("", "保存成功");
                }
            }
            return View(model);
        }

        public async Task<ActionResult> edit(int id)
        {
            var model = await service.searchByid(id);
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> edit(MaterialInfo model)
        {
            if (ModelState.IsValid)
            {
                var result = await service.update(model);
                if (!result.success)
                {
                    ModelState.AddModelError("", result.message);
                }
                else
                {
                    ModelState.AddModelError("", "保存成功");
                }
            }
            return View(model);
        }

        public async Task<ActionResult> delete(int id,MaterialInfo condition)
        {
            var result = await service.deleteByIdAsync(id);
            if (!result.success)
            {
                return View("Error", new string[] { result.message });
            }
            return RedirectToAction("Index", condition);
        }

        public ActionResult selectList()
        {
            return View();
        }
        public JsonResult list(MaterialInfoQuery condition)
        {
            ViewBag.condition = condition;
            Pager<List<MaterialInfo>> pager = new Pager<List<MaterialInfo>>();
            pager = service.searchByCondition(pager, condition);
            JsonResult result = Json(pager.data);
            return result;
        }

        public async Task<JsonResult> searchModel(int id)
        {
            var result = await service.searchByid(Convert.ToInt32(id));
            return Json(result);
        }
    }
}

123TribeFrameworker/Views/MaterialInfo/Index.cshtml
@{
    ViewBag.Title = "物料查询";
}
@using _123TribeFrameworker.Entity
@model Pager<List<MaterialInfo>>
<script type="text/javascript">
    $(function () {
        $('#materialTable').datatable({ sortable: true });
        $('#dataPager').pager({
            page: @Model.page,
            recTotal: @Model.recTotal,
            recPerPage:@Model.recPerPage,
            onPageChange: function(state, oldState) {
                if (typeof(oldState.page)!="undefined" && state.page !== oldState.page) {
                    var href = $('#searchForm').attr("action");
                    href = href + "?page=" + state.page;
                    $('#searchForm').attr("action", href);
                    $('#searchForm').submit();
                }
            }
        });
    })
</script>
<div>
    @using (Html.BeginForm())
    {
        <div class="col-md-3  form-group">
            <div class="input-control has-label-left-lg">
                <input id="materialName" name="materialName" value="@ViewBag.condition.materialName" type="text" class="form-control">
                <label for="materialName" class="input-control-label-left"> 产品名称:</label>
            </div>
        </div>
            <div class="col-md-3  form-group">
                <div class="input-control has-label-left">
                    <input id="alias" name="alias" value="@ViewBag.condition.alias" type="text" class="form-control">
                    <label for="alias" class="input-control-label-left"> 别名:</label>
                </div>
            </div>
            <div class="col-md-3  form-group">
                <div class="input-control has-label-left">
                    <input id="mat_size" name="mat_size" value="@ViewBag.condition.mat_size" type="text" class="form-control">
                    <label for="mat_size" class="input-control-label-left"> 规格:</label>
                </div>
            </div>
            <div class="col-md-3  form-group">
                <div class="input-control has-label-left">
                    <input id="remark" name="remark" value="@ViewBag.condition.remark" type="text" class="form-control">
                    <label for="remark" class="input-control-label-left"> 备注:</label>
                </div>
            </div>
            <button class="btn btn-primary" type="submit">查询</button>
            @Html.ActionLink("新增", "add", null, new { @class = "btn btn-warning" })
    }

    <table id="materialTable" class="table datatable table-striped table-condensed">
        <thead>
            <tr>
                <th data-width="50">#</th>
                <th >产品名称</th>
                <th >别名</th>
                <th>规格</th>
                <th>单位</th>
                <th>采购价</th>
                <th>建议零售价</th>
                <th>库存警报值</th>
                <th>备注</th>
                <th  data-width="160">操作</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.data.Count > 0)
            {
                for (int i = 0; i < Model.data.Count; i++)
                {
                    <tr>
                        <td>@((Model.page - 1) * Model.recPerPage + i + 1 )</td>
                        <td>@Model.data[i].materialName</td>
                        <td>@Model.data[i].alias</td>
                        <td>@Model.data[i].mat_size</td>
                        <td>@Model.data[i].unit</td>
                        <td>@Model.data[i].referencePriceIn</td>
                        <td>@Model.data[i].referencePriceOut</td>
                        <td>@Model.data[i].alarmCount</td>
                        <td>@Model.data[i].remark</td>
                        <td>
                            @using (Html.BeginForm("delete", "MaterialInfo", new
                            {
                                id = Model.data[i].id,
                                alias = ViewBag.condition.alias,
                                materialName = ViewBag.condition.materialName,
                                remark = ViewBag.condition.remark,
                                mat_size = ViewBag.condition.mat_size
                            }))
                            {
                                @Html.ActionLink("修改", "edit", new { id = Model.data[i].id }, new { @class = "btn btn-warning" })
                                <button class="btn btn-danger" type="submit">删除</button>
                            }
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div style="margin-top:-20px"><ul id="dataPager" class="pager"></ul></div>

</div>

123TribeFrameworker/Views/MaterialInfo/add.cshtml
@using _123TribeFrameworker.Entity
@model MaterialInfo
@{
    ViewBag.Title = "物料增加";
}
<div style="color:red">@Html.ValidationSummary(false)</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 style="text-align:center">添加物料</h4>
    </div>
    @using (Html.BeginForm())
    {
        <label for="materialName" class="required">物料名称：</label>
        @Html.TextBoxFor(x => x.materialName, new { @class = "form-control" });
        <label for="alias">别名：</label>
        @Html.TextBoxFor(x => x.alias, new { @class = "form-control" });
        <label for="unit">单位：</label>
        @Html.TextBoxFor(x => x.unit, new { @class = "form-control" });
        <label for="mat_size">规格：</label>
        @Html.TextBoxFor(x => x.mat_size, new { @class = "form-control" });
        <label for="referencePriceIn" class="required">采购价：</label>
        @Html.TextBoxFor(x => x.referencePriceIn, new { @class = "form-control" });
        <label for="referencePriceOut">建议零售价：</label>
        @Html.TextBoxFor(x => x.referencePriceOut, new { @class = "form-control" });
        <label for="alarmCount">库存警报值：</label>
        @Html.TextBoxFor(x => x.alarmCount, new { @class = "form-control" });
        <label for="remark">备注：</label>
        @Html.TextBoxFor(x => x.remark, new { @class = "form-control" });
        <div>
            <button type="submit" class="btn btn-primary">保存</button>
            @Html.ActionLink("返回", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

123TribeFrameworker/Views/MaterialInfo/edit.cshtml
@using _123TribeFrameworker.Entity
@model MaterialInfo
@{
    ViewBag.Title = "物料修改";
}
<div style="color:red">@Html.ValidationSummary(false)</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 style="text-align:center">@Model.materialName</h4>
    </div>
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(x => x.id)
        <div class="panel-body">
            <label for="materialName">产品名称：</label>
            @Html.TextBoxFor(x => x.materialName, new { @class = "form-control" })
            <label for="alias">别名：</label>
            @Html.TextBoxFor(x => x.alias, new { @class = "form-control" })
            <label for="unit">单位：</label>
            @Html.TextBoxFor(x => x.unit, new { @class = "form-control" })
            <label for="mat_size">规格：</label>
            @Html.TextBoxFor(x => x.mat_size, new { @class = "form-control" })
            <label for="referencePriceIn" class="required">采购价：</label>
            @Html.TextBoxFor(x => x.referencePriceIn, new { @class = "form-control" })
            <label for="referencePriceOut">建议零售价：</label>
            @Html.TextBoxFor(x => x.referencePriceOut, new { @class = "form-control" })
            <label for="referencePriceOut">库存警报值：</label>
            @Html.TextBoxFor(x => x.alarmCount, new { @class = "form-control" })
            <label for="remark">备注：</label>
            @Html.TextBoxFor(x => x.remark, new { @class = "form-control" })
            <div>
                <button type="submit" class="btn btn-primary">保存</button>
                @Html.ActionLink("返回", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    }
</div>

123TribeFrameworker/Views/MaterialInfo/selectList.cshtml
@{
    Layout = null;
}
<script type="text/javascript">
    var colsList = [
    { name: 'id', width: 1, label: 'id' },
    { name: 'materialName', label: '物料名称' },
    { name: 'alias', width: 1, label: '别名' },
    { name: 'mat_size', label: '规格' },
    { name: 'unit', width: 1, label: '单位' },
    { name: 'referencePriceIn', width: 1, label: '成本' },
    { name: 'remark', label: '备注' }
    ]
    $(function () {
        $("#ListTable").datagrid({
            dataSource: {
                cols: colsList
            },
            states: {
                pager: { page: 1, recPerPage: 5 }
            },
            sortable: true,
            checkable: true,
            responsive: true,
            height: 'page'
        })
    })
    function search() {
        $.ajax({
            //几个参数需要注意一下
            type: "POST",//方法类型
            dataType: "json",//预期服务器返回的数据类型
            url: "/materialInfo/list",//url
            data: $('#myForm').serialize(),
            success: function (result) {
                var myDataGrid = $('#ListTable').data('zui.datagrid');
                myDataGrid.setDataSource(result)
                myDataGrid.render()
            }
        });
    }
</script>
<body>
    <form id="myForm" class="form-horizontal">
        <div class="form-group">
            <div class="col-md-5">
                <input name="materialName" type="text" class="form-control" placeholder="产品名称">
            </div>
            <div class="col-md-3">
                <input name="alias" type="text" class="form-control" placeholder="别名">
            </div>
            <div class="col-md-3">
                <input name="mat_size" type="text" class="form-control" placeholder="规格">
            </div>
            
        </div>
        <div class="form-group">
            <div class="col-md-8">
                <input name="remark" type="text" class="form-control" placeholder="备注">
            </div>
            <div class="col-md-2">
                <button class="btn btn-primary" type="button" onclick="search()">查询</button>
            </div>
        </div>
    </form>

    <div id="ListTable" class="datagrid">
        <div class="datagrid-container"></div>
        <div class="pager"></div>
    </div>
</body>