123TribeFrameworker/Controllers/OrderDetailInfoController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using _123TribeFrameworker.Entity;
using _123TribeFrameworker.Models.BussinessModels;
using _123TribeFrameworker.Models.QueryModel;
using _123TribeFrameworker.Services;
using _123TribeFrameworker.Services.Layer;
using Newtonsoft.Json;
using Unity.Attributes;

namespace _123TribeFrameworker.Controllers
{
    public class OrderDetailInfoController : Controller
    {
        [Dependency]
        public IOrderInfoService Orderservice { get; set; }
        [Dependency]
        public IInventoryService invnetoryService { get; set; }
        [Dependency]
        public IOrderDetailInfoService detailService { get; set; }
        [Dependency]
        public IInStorageRecordService inStroageService { get; set; }

        // GET: OrderDetailInfo
        /// <summary>
        /// 初始化
        /// </summary>
        /// <param name="pager"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        public ActionResult Index(Pager<List<OrderDetailInfo>> pager, OrderDetailInfoQuery condition)
        {
            ViewBag.condition = condition;
            return View(pager);
        }
        /// <summary>
        /// 查询
        /// </summary>
        /// <param name="pager"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        public ActionResult search(Pager<List<OrderDetailInfo>> pager, OrderDetailInfoQuery condition)
        {
            pager = detailService.searchByCondition(pager, condition);
            ViewBag.condition = condition;
            return View("Index", pager);
        }

        #region 订单修改
        public ActionResult update(string orderNo)
        {
            OrderDetailInfoQuery condition = new OrderDetailInfoQuery()
            {
                orderNo = orderNo,
                status = "generated"
            };
            var list = detailService.searchAllByCondition(condition);
            if (list.Count==0)
            {
                ViewBag.returnUrl = "/OrderInfo/search?orderNo="+orderNo;
                return View("Error", new string[] { "未收货订单中查询不到" + orderNo + "，请检查订单是否已收货完成或取消" });
            }
            return View(list);
        }
        /// <summary>
        /// 删除详细
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> deleteDetail(int id)
        {
            var result = await detailService.deleteById(id,User.Identity.Name);
            ViewBag.returnUrl = "/OrderDetailInfo/update?orderNo=" + result.data.orderNo;
            if (result.success)
            {
                ViewBag.Msg = "删除成功";
                return View("Success");
            }
            return View("Error", new string[] { result.message });
        }
        /// <summary>
        ///修改详细
        /// </summary>
        /// <param name="id"></param>
        /// <param name="orderNo"></param>
        /// <returns></returns>
        public async Task<ActionResult> updateDetail(int id,string orderNo)
        {
            var model = await detailService.searchById(id);
            if (model==null)
            {
                ViewBag.returnUrl = "/OrderDetailInfo/update?orderNo="+ orderNo;
                return View("Error", new string[] { "订单已被删除" });
            }
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> updateDetail(OrderDetailInfo model)
        {
            model.lastUpdatedBy = User.Identity.Name;
            model.lastUpdatedDate = DateTime.Now;
            var result = await detailService.updateDetail(model);
            if (!result.success)
            {
                ViewBag.returnUrl = "/OrderDetailInfo/updateDetail?id=" + model.id+"&orderNo="+model.orderNo;
                return View("Error",new string[] { "操作失败："+result.message});
            }
            ViewBag.returnUrl = "/OrderDetailInfo/update?orderNo=" + model.orderNo;
            ViewBag.Msg = "修改成功";
            return View("Success");
        }
        /// <summary>
        /// 增加详细
        /// </summary>
        /// <param name="orderNo"></param>
        /// <returns></returns>
        public ActionResult addDetail([Required]string orderNo)
        {
            ViewBag.orderNo = orderNo;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> addDetail(OrderDetailInfo model)
        {
            model.createdBy = User.Identity.Name;
            if (model.num <= 0)
            {
                ModelState.AddModelError("", "数量必须为正数");
                ViewBag.orderNo = model.orderNo;
                return View();
            }
            var result = await detailService.addDetail(model);
            if (!result.success)
            {
                ModelState.AddModelError("",result.message);
                ViewBag.orderNo = model.orderNo;
                return View();
            }
            ViewBag.returnUrl = "/OrderDetailInfo/update?orderNo="+model.orderNo;
            ViewBag.Msg = "增加成功";
            return View("Success");
        }
        #endregion

        #region 订单收货
        /// <summary>
        /// 订单收货
        /// </summary>
        /// <param name="orderNo"></param>
        /// <returns></returns>
        public ActionResult receive(string orderNo)
        {
            OrderDetailInfoQuery condition = new OrderDetailInfoQuery();
            condition.orderNo = orderNo;
            condition.status = "generated";
            var result = detailService.searchAllByCondition(condition);
            if (result.Count==0)
            {
                ViewBag.returnUrl = "/OrderInfo/Index";
                return View("Error", new string[] { "未收货订单中查询不到"+orderNo + "，请检查订单是否已收货完成或取消" });
            }
            return View(result);
        }
        /// <summary>
        /// 增加库存收货
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> receive(List<InStorageRecord> list, [Required]string receivedOrder)
        {
            var orderNo = list.First().orderNo;
            ViewBag.returnUrl = "/OrderDetailInfo/receive?orderNo="+orderNo;
            //有可能存在本产品没发过来的情况 也就是为0的情况
            var countCheck = list.Where(x => x.countReal < 0 ).Count();
            if (countCheck > 0)
            {
                return View("Error",new string[] { "实收数量必须为正数" });
            }
            var priceCheck = list.Where(x => x.priceIn <= 0).Count();
            if (priceCheck>0)
            {
                return View("Error", new string[] { "实际进价必须为正数" });
            }
            
            Result<int> result = await detailService.receiveOrder(list, receivedOrder, User.Identity.Name);
            if (result.success)
            {
                ViewBag.returnUrl = "/OrderInfo/search?orderNo="+orderNo;
                ViewBag.Msg = "订单收货成功！";
                return View("Success");
            }
            return View("Error", new string[] { result.message });
        }
        #endregion

        #region 创建订单

        public async Task<ActionResult> add(Pager<List<InventorySimpleModel>> pager)
        {
            pager = new Pager<List<InventorySimpleModel>>(50);
            pager = await invnetoryService.searchByNumOrder(pager);
            return View(pager);
        }
        [HttpPost]
        public async Task<ActionResult> generateOrder(string jsonOrder)
        {
            
            var orderList = JsonConvert.DeserializeObject<List<OrderDetailInfo>>(jsonOrder);
            var priceList = JsonConvert.DeserializeObject<List<PriceCount>>(jsonOrder);
            var sumPrice = priceList.Sum(x => x.referencePriceIn * x.num);
            
            var orderResult = await Orderservice.addOrder(orderList, User.Identity.Name, sumPrice);
            if (orderResult.success)
            {
                ViewBag.returnUrl = "/OrderInfo/search?orderNo="+ orderResult.data.First().orderNo;
                ViewBag.Msg = "订单生成成功:" + orderResult.data.First().orderNo;
                return View("Success");
            }
            else
            {
                ViewBag.returnUrl = "/OrderDetailInfo/add";
                return View("Error", new string[] { orderResult.message });
            }
            
        }
        #endregion

        #region 处理异常订单
        public ActionResult dealReceivedOrder(string orderNo)
        {
            InStorageRecordQuery condition = new InStorageRecordQuery();
            condition.orderNo = orderNo;
            var instorageRecords = inStroageService.searchAllByCondition(condition);
            if (instorageRecords.Where(x=>x.countReal!=x.countReference).Count()==0)
            {
                ViewBag.returnUrl = "/OrderInfo/search?orderNo=" + orderNo;
                return View("Error", new string[] { "订单已被处理" });
            }
            return View(instorageRecords);
        }
        [HttpPost]
        public async Task<ActionResult> dealReceivedOrder(List<InStorageRecord> list)
        {
            var orderNo = list.First().orderNo;
            ViewBag.returnUrl = "/OrderDetailInfo/dealReceivedOrder?orderNo=" + orderNo;
            var countCheck = list.Where(x => x.countReal < 0).Count();
            if (countCheck > 0)
            {
                return View("Error", new string[] { "实收数量必须为正数" });
            }
            Result<int> result = await detailService.dealReceivedOrder(list, User.Identity.Name);
            if (result.success)
            {
                ViewBag.returnUrl = "/OrderInfo/Index?orderNo=" + orderNo;
                ViewBag.Msg = "订单异常处理成功！";
                return View("Success");
            }
            return View("Error", new string[] { result.message });
        }
        #endregion
    }

123TribeFrameworker/Controllers/OrderInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using _123TribeFrameworker.Entity;
using _123TribeFrameworker.Models.QueryModel;
using _123TribeFrameworker.Services;
using Newtonsoft.Json;
using Unity.Attributes;

namespace _123TribeFrameworker.Controllers
{
    public class OrderInfoController : Controller
    {
        [Dependency]
        public IOrderInfoService service { get; set; }

        // GET: OrderInfo
        public ActionResult Index(Pager<List<OrderInfo>> pager, OrderInfoQuery condition)
        {
            ViewBag.condition = condition;
            //pager = service.searchByCondition(pager, condition);
            return View(pager);
        }
        public ActionResult search(Pager<List<OrderInfo>> pager, OrderInfoQuery condition)
        {
            ViewBag.condition = condition;
            pager = service.searchByCondition(pager, condition);
            return View("Index",pager);
        }
        /// <summary>
        /// 删除订单
        /// </summary>
        /// <param name="orderNo"></param>
        /// <returns></returns>
        public async Task<ActionResult> delete(string orderNo)
        {
            var result = await service.deleteByOrderNo(orderNo);
            if (!result.success)
            {
                ViewBag.returnUrl = "/OrderInfo/search?orderNo="+orderNo;
                return View("Error", new string[] { result.message });
            }
            else
            {
                ViewBag.returnUrl = "/OrderInfo/Index";
                ViewBag.Msg = "订单删除成功";
                return View("Success");
            }
        }


    }
}

123TribeFrameworker/Views/OrderDetailInfo/Index.cshtml
@using _123TribeFrameworker.Entity;
@using _123TribeFrameworker.Infrastructrue;
@model Pager<List<OrderDetailInfo>>
@{
    ViewBag.title = "订单详情";
}
<script type="text/javascript">
    $(function () {
        $('#myDataGrid').datagrid({
            sortable: true,
            checkable:true,
            selectable:false,
            height:410
        });
        $('#myPager').pager({
            page: @Model.page,
            recTotal: @Model.recTotal,
            recPerPage:@Model.recPerPage,
            onPageChange: function(state, oldState) {
                if (typeof(oldState.page)!="undefined" && state.page !== oldState.page) {
                    var href = $('#searchForm').attr("action");
                    href = href + "?page=" + state.page;
                    $('#searchForm').attr("action", href);
                    $('#searchForm').submit();
                }
            }
        });
    })
    //function updateOrder(){
    //    if (checkCondition()) {
    //        var myTable = $('#myDataGrid').data('zui.datagrid');
    //        var data = myTable.getCheckItems();
    //        var orderNo = data[0][0];
    //        if (confirm("确定修改订单"+orderNo+"？")) {
    //            location.href="/OrderDetailInfo/update?orderNo="+orderNo;
    //        }
    //    }
    //}
    function checkCondition(){
        var myTable = $('#myDataGrid').data('zui.datagrid');
        var data = myTable.getCheckItems();
        var flag = true;
        if (data.length==0) {
            bootbox.alert('请选中一个订单')
            flag = false;
        }
        else if (data.length>1) {
            bootbox.alert('每次只能处理一个订单')
            flag = false;
        }
        else{
            var status = data[0][5];
            if (status!="已下发") {
                bootbox.alert("订单已收货，无法重复操作")
                flag = false;
            }
        }
        return flag;
    }
</script>
<form action="/OrderDetailInfo/search" method="post" id="searchForm" class="form-horizontal">
    <div class="form-group">
        <div class="col-md-3">
            <div class="input-control has-label-left-lg">
                <input id="orderNo" name="orderNo" value="@ViewBag.condition.orderNo" type="text" class="form-control">
                <label for="orderNo" class="input-control-label-left"> 进货单号:</label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-control has-label-left-lg">
                <select id="status" name="status" value="@ViewBag.condition.status" class="chosen-select form-control">
                    <option value=""></option>
                    @foreach (var item in Html.orderStatus())
                    {
                        <option value="@item.Key">@item.Value</option>
                    }
                </select>
                <label for="status" class="input-control-label-left"> 单据状态:</label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-control has-label-left-lg">
                <input id="materialName" name="materialName" value="@ViewBag.condition.materialName" type="text" class="form-control">
                <label for="materialName" class="input-control-label-left"> 产品名称:</label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-control has-label-left">
                <input id="alias" name="alias" value="@ViewBag.condition.alias" type="text" class="form-control">
                <label for="alias" class="input-control-label-left"> 别名:</label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <div class="input-control has-label-left">
                <input id="mat_size" name="mat_size" value="@ViewBag.condition.mat_size" type="text" class="form-control">
                <label for="mat_size" class="input-control-label-left"> 规格:</label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-control has-label-left-lg">
                <input id="createdDateBegin" name="createdDateBegin" value="@ViewBag.condition.createdDateBegin" type="text" class="form-control form-datetime">
                <label for="createdDateBegin" class="input-control-label-left"> 创建时间1:</label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-control has-label-left-lg">
                <input id="createdDateEnd"name="createdDateEnd" value="@ViewBag.condition.createdDateEnd" type="text" class="form-control form-datetime">
                <label for="createdDateEnd" class="input-control-label-left"> 创建时间2:</label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-control has-label-left-lg">
                <input id="receivedDateBegin" name="receivedDateBegin" value="@ViewBag.condition.receivedDateBegin" type="text" class="form-control form-datetime">
                <label for="receivedDateBegin" class="input-control-label-left"> 收货时间1:</label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <div class="input-control has-label-left-lg">
                <input id="receivedDateEnd"  name="receivedDateEnd" value="@ViewBag.condition.receivedDateEnd" type="text" class="form-control form-datetime">
                <label for="receivedDateEnd" class="input-control-label-left"> 收货时间2:</label>
            </div>
        </div>
        <button class="btn btn-primary" type="submit">查询</button>
    </div>
</form>
<table class="table datatable table-striped" id="myDataGrid">
    <thead>
        <tr>
            <th>
                进货单号
            </th>
            <th>
                产品名称
            </th>
            <th>
                别名
            </th>
            <th>
                规格
            </th>
            <th>
                数量
            </th>
            <th>
                订单状态
            </th>
            <th>
                创建时间
            </th>
            <th>
                收货时间
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.data.Count > 0)
        {
            foreach (var item in Model.data)
            {
                <tr>
                    <td>@item.orderNo</td>
                    <td>@item.materialInfo.materialName</td>
                    <td>@item.materialInfo.alias</td>
                    <td>@item.materialInfo.mat_size</td>
                    <td>@item.num</td>
                    <td>@item.orderInfo.orderStatus.status</td>
                    <td>@item.createdDate</td>
                    <td>@item.orderInfo.receivedDate</td>
                </tr>
            }
        }
    </tbody>
</table>
<ul id="myPager" class="pager"></ul>

123TribeFrameworker/Views/OrderDetailInfo/addDetail.cshtml
@{
    ViewBag.title = "订单明细增加";
}
<script type="text/javascript">
    function chooseMaterial() {
        var myDataGrid = $('#ListTable').data('zui.datagrid');
        var data = myDataGrid.getCheckItems();
        if (data.length == 1) {
            setInput(data[0])
        } else {
            bootbox.alert("必须选择一条且仅能选择一条产品信息")
        }
        var context = myDataGrid.getData()
        for (var i = 0; i < context.length; i++) {
            myDataGrid.checkRow(i, false);
        }
        myDataGrid.render()
    }
    function setInput(materialInfo) {
        $('#materialId').val(materialInfo.id);
        $('#materialName').val(materialInfo.materialName);
        $('#alias').val(materialInfo.alias);
        $('#mat_size').val(materialInfo.mat_size);
        $('#unit').val(materialInfo.unit);
        $('#referencePriceIn').val(materialInfo.referencePriceIn);
        $('#remark').val(materialInfo.remark);
        $('#num').val(0)
    }
</script>
<div style="color:red">
    @Html.ValidationSummary(false)
</div>
<div class="panel panel-primary">
    <div class="panel-heading" style="text-align:center">
        订单明细添加
    </div>
    <div class="panel-body">
        <form class="form-horizontal" action="/OrderDetailInfo/addDetail" method="post">
            <input hidden="hidden" name="orderNo" value="@ViewBag.orderNo" />
            <input hidden="hidden" name="materialId" id="materialId"/>
            <div class="form-group">
                <label for="materialName" class="col-md-2">商品名称</label>
                <div class="col-md-3">
                    <input type="text" class="form-control" readonly="readonly" name="materialName" id="materialName" />
                </div>
                <div class="col-md-1">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">选择</button>
                    </div>
                <label for="mat_size" class="col-md-2">规格</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" readonly="readonly" id="mat_size" />
                </div>
            </div>
            <div class="form-group">
                <label for="num" class="col-md-2">数量</label>
                <div class="col-md-4">
                    <input type="number" class="form-control" name="num" id="num" />
                </div>
                <label for="unit" class="col-md-2">单位</label>
                <div class="col-md-4">
                    <input type="text" readonly="readonly" class="form-control" id="unit" />
                </div>
            </div>
            <div class="form-group">
                <label for="alias" class="col-md-2">别名</label>
                <div class="col-md-4">
                    <input type="text" readonly="readonly" class="form-control"id="alias" />
                </div>
                <label for="referencePriceIn" class="col-md-2">成本</label>
                <div class="col-md-4">
                    <input type="text" readonly="readonly" class="form-control" id="referencePriceIn" />
                </div>
            </div>
            <div class="form-group">
                <label for="remark" class="col-md-2">备注</label>
                <div class="col-md-10">
                    <input type="text" readonly="readonly" class="form-control" id="remark" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2"></label>
                <div class="col-md-5">
                    <button type="submit" class="btn btn-primary btn-block">保存</button>
                </div>
                <div class="col-md-5">
                    @Html.ActionLink("返回", "update", new { orderNo = ViewBag.orderNo }, new { @class = "btn btn-default btn-block" })
                </div>
            </div>
        </form>
    </div>
</div>

<!-- 对话框HTML -->
<div class="modal fade" data-moveable="true" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>产品选择</h3>
            </div>
            <div class="modal-body">
                @Html.Action("selectList", "materialInfo")
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="chooseMaterial()">选择</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>

123TribeFrameworker/Views/OrderDetailInfo/dealReceivedOrder.cshtml
@using _123TribeFrameworker.Entity
@using _123TribeFrameworker.Models.BussinessModels
@model List<InStorageRecordModel>
@{
    ViewBag.title = "异常订单处理";
}
<script type="text/javascript">
    function receiveOrder() {
        bootbox.prompt("请输入回执单号", function (receiveOrder) {
            if (receiveOrder == null) {
                return;
            }
            else if (receiveOrder == "") {
                bootbox.alert("回执单号不能为空");
            } else {
                $('input[name="receivedOrder"]').val(receiveOrder)
                $('#myForm').submit();
            }
        })
    }
</script>
<div style="color:red">
    @Html.ValidationSummary(false)
</div>
<div class="panel panel-primary">
    <div class="panel-heading" style="text-align:center">
        <h3>订单入库</h3>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" action="/OrderDetailInfo/dealReceivedOrder" method="post" id="myForm">
            <input hidden="hidden" name="receivedOrder" />
            @for (int i = 0; i < Model.Count; i++)
            {
                @Html.HiddenFor(x => x[i].materialId)
                @Html.HiddenFor(x => x[i].orderNo)
                @Html.HiddenFor(x => x[i].receivedOrder)
                <div class="form-group">
                    <label class="col-md-1">产品名称:</label>
                    <div class="col-md-2">
                        <input class="form-control" readonly="readonly" type="text" value="@Model[i].materialName" />
                    </div>
                    <label for="countReference" class="col-md-1">应收数量:</label>
                    <div class="col-md-1">
                        <input class="form-control" readonly="readonly" type="text" value="@Model[i].countReference" />
                    </div>
                    <label for="count" class="col-md-1">实收数量:</label>
                    <div class="col-md-1">
                        <input class="form-control" readonly="readonly" type="number" value="@Model[i].countReal" />
                    </div>
                    <label for="priceIn" class="col-md-1">实际进价:</label>
                    <div class="col-md-1">
                        @Html.TextBoxFor(x => x[i].priceIn, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                    <label for="count" class="col-md-1">补充数量:</label>
                    <div class="col-md-1">
                        @{
                            var supplementCount = Model[i].countReference - Model[i].countReal;
                            if (supplementCount == 0)
                            {
                                <input class="form-control" type="number" readonly="readonly" value="@supplementCount" name="[@i].countReal" />
                            }
                            else
                            {
                                <input class="form-control" type="number" value="@supplementCount" name="[@i].countReal" />
                            }
                        }
                    </div>
                </div>
                <hr>
            }
            <div class="col-md-6">
                @Html.ActionLink("返回", "Index", "OrderInfo", null, new { @class = "btn btn-default btn-block" })
            </div>
            <div class="col-md-6">
                <button type="submit" class="btn btn-primary btn-block">补充收货</button>
            </div>
        </form>
    </div>
</div>

123TribeFrameworker/Views/OrderDetailInfo/receive.cshtml
@using _123TribeFrameworker.Entity
@model List<OrderDetailInfo>
@{
    ViewBag.title = "订单入库";
}
<script type="text/javascript">
    function receiveOrder() {
        bootbox.prompt("请输入回执单号", function (receiveOrder) {
            if (receiveOrder == null) {
                return;
            }
            else if (receiveOrder == "") {
                bootbox.alert("回执单号不能为空");
            } else {
                $('input[name="receivedOrder"]').val(receiveOrder)
                $('#myForm').submit();
            }
        })
    }
</script>
<div style="color:red">
    @Html.ValidationSummary(false)
</div>
<div class="panel panel-primary">
    <div class="panel-heading" style="text-align:center">
        <h3>订单入库</h3>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" action="/OrderDetailInfo/receive" method="post" id="myForm">
            <input hidden="hidden" name="receivedOrder" />
            @for (int i = 0; i < Model.Count; i++)
            {
                <input hidden="hidden" name="[@i].materialId" value="@Model[i].materialId" />
                <input hidden="hidden" name="[@i].orderNo" value="@Model[i].orderNo" />
                
                <div class="form-group">
                    <label class="col-md-1">产品名称:</label>
                    <div class="col-md-2">
                        <input class="form-control" type="text" readonly="readonly" value="@Model[i].materialName" />
                    </div>
                    <label for="countReference" class="col-md-1">应收数量:</label>
                    <div class="col-md-1">
                        <input class="form-control" type="number" readonly="readonly" value="@Model[i].num" name="[@i].countReference" />
                    </div>
                    <div>
                        <label for="count" class="col-md-1">实收数量:</label>
                        <div class="col-md-1">
                            <input class="form-control" type="number" value="@Model[i].num" name="[@i].countReal" />
                        </div>
                    </div>
                    <label class="col-md-1">参考进价:</label>
                    <div class="col-md-1">
                        <input class="form-control" type="number" readonly="readonly" value="@Model[i].materialInfo.referencePriceIn" />
                    </div>
                    <div>
                        <label for="priceIn" class="col-md-1">实际进价:</label>
                        <div class="col-md-1">
                            <input class="form-control" type="number" value="@Model[i].materialInfo.referencePriceIn" name="[@i].priceIn" />
                        </div>
                    </div>
                </div>
                <hr>
            }
            <div class="col-md-6">
                @Html.ActionLink("返回", "Index", "OrderInfo", null, new { @class = "btn btn-default btn-block" })
            </div>
            <div class="col-md-6">
                <button type="button" class="btn btn-primary btn-block" onclick="receiveOrder()">收货</button>
            </div>
            
        </form>
    </div>
</div>

123TribeFrameworker/Views/OrderDetailInfo/update.cshtml
@using _123TribeFrameworker.Entity
@model List<OrderDetailInfo>

@{
    ViewBag.Title = "订单修改";
}

<div class="panel panel-primary">
    <div class="panel-heading" style="text-align:center">
        @Model.First().orderNo
    </div>
    <div class="panel-body">
        @Html.ActionLink("新增明细", "addDetail",new { orderNo= @Model.First().orderNo },new { @class = "btn btn-warning" })
        @Html.ActionLink("返回", "search","OrderInfo", new { orderNo = @Model.First().orderNo }, new { @class = "btn btn-default" })
        <table id="menu" class="table table-striped table-condensed">
            <tr>
                <th>产品名称</th>
                <th>规格</th>
                <th>数量</th>
                <th>单位</th>
                <th>成本</th>
                <th>操作</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.materialName</td>
                    <td>@item.materialInfo.mat_size</td>
                    <td>@item.num</td>
                    <td>@item.materialInfo.unit</td>
                    <td>@item.materialInfo.referencePriceIn</td>
                    <td>
                        @using (Html.BeginForm("deleteDetail", "OrderDetailInfo", new { id = item.id }))
                        {
                            <button type="submit" class="btn btn-danger">删除</button>
                            @Html.ActionLink("修改", "updateDetail", new { id = @item.id, orderNo=@item.orderNo }, new { @class = "btn btn-warning" })
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>